name: studya_io
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioing at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1 

dependencies:
  provider:
  google_fonts:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  url_launcher: ^6.0.20
  dropdown_textfield: ^1.2.0
  auto_size_text: ^3.0.0
  quickalert: ^1.1.0
  awesome_dialog: ^3.2.1
  flutter_switch: ^0.3.2
  audioplayers: ^6.1.0
  flutter_volume_controller: ^1.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.2.0+3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  flutter_colorpicker: 1.1.0
  sqflite: ^2.0.0+4
  uuid: ^3.0.6

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  android: true
  image_path_android: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.11
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  fonts:
    - family: MuseoModerno
      fonts:
        - asset: assets/fonts/MuseoModerno-Bold.ttf
        - asset: assets/fonts/MuseoModerno-VariableFont_wght.ttf
        - asset: assets/fonts/MuseoModerno-Black.ttf
        - asset: assets/fonts/MuseoModerno-BlackItalic.ttf
        - asset: assets/fonts/MuseoModerno-BoldItalic.ttf
        - asset: assets/fonts/MuseoModerno-ExtraBold.ttf
        - asset: assets/fonts/MuseoModerno-ExtraBoldItalic.ttf
        - asset: assets/fonts/MuseoModerno-ExtraLight.ttf
        - asset: assets/fonts/MuseoModerno-ExtraLightItalic.ttf
        - asset: assets/fonts/MuseoModerno-Italic.ttf
        - asset: assets/fonts/MuseoModerno-Light.ttf
        - asset: assets/fonts/MuseoModerno-LightItalic.ttf
        - asset: assets/fonts/MuseoModerno-Medium.ttf
        - asset: assets/fonts/MuseoModerno-MediumItalic.ttf
        - asset: assets/fonts/MuseoModerno-Regular.ttf
        - asset: assets/fonts/MuseoModerno-SemiBold.ttf
        - asset: assets/fonts/MuseoModerno-SemiBoldItalic.ttf
        - asset: assets/fonts/MuseoModerno-Thin.ttf
        - asset: assets/fonts/MuseoModerno-ThinItalic.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf  
        - asset: assets/fonts/MontserratLight.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratExtraBold.ttf
          weight: 800

    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600

    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500

    - family:  CustomNavBarIcons
      fonts:
       - asset: assets/custom_nav_bar_icons/fonts/CustomNavBarIcons.ttf
    
    - family:  CustomIcons
      fonts:
       - asset: assets/custom_icons/fonts/CustomIcons.ttf

    - family:  CustomTimerIcons
      fonts:
       - asset: assets/custom_timer_icons/fonts/CustomTimerIcons.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:

 
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/banner_splash.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png
    - assets/images/onboarding_4.png
    - assets/alarm_sounds/
    - assets/alarm_sounds/flipcard.mp3
    - assets/alarm_sounds/default_alarm_sound.mp3
    - assets/alarm_sounds/digital_beep_alarm_sound.mp3
    - assets/alarm_sounds/bliss_alarm_sound.mp3
    - assets/alarm_sounds/classic_alarm_sound.mp3

flutter_native_splash:
  # Splash screen background color
  color: "#42a5f5"

  # Splash screen image (main icon in the center)
  image: assets/images/splash.png

  # Branding image at the bottom
  branding: assets/images/banner_splash.png

  # Settings for Android 12+ (special handling for splash screens)
  android_12:
    image: assets/images/splash.png
    branding: assets/images/banner_splash.png
    # Optional: icon_background_color can be set here for Android 12
    # icon_background_color: "#42a5f5"

  # Enable splash screens for all platforms
  android: true
  ios: true
  web: true

  # Optional dark mode settings
  color_dark: "#042a49" # Dark background color
  image_dark: assets/images/splash.png
  branding_dark: assets/images/banner_splash.png

