/// Flutter icons CustomNavBarIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomNavBarIcons
///      fonts:
///       - asset: fonts/CustomNavBarIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class CustomNavBarIcons {
  CustomNavBarIcons._();

  static const _kFontFam = 'CustomNavBarIcons';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData timer_nav_bar_ =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // ignore: constant_identifier_names
  static const IconData flash_card__nav_bar_ =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  
}
